### ISSUE TITLE
Preferring inlined types over type stubs

### ISSUE THREAD

**Issue by erictraut** [srittau/type-stub-pep#93] opened 2021-01-16 17:56 UTC
We think it’s important to encourage library authors to use inlined types wherever possible. Type stubs will still be needed in exceptional cases, but over time we hope that they are used only for libraries that are implemented in languages other than Python. Of course, they will continue to be needed for other reasons in the short term. I wonder if we should include language in this PEP that makes it clear that inlined types are preferred? If not in this PEP, where else would we include such guidance?

(Incidentally, [this documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md) comprises our guidance to library authors and covers both inlined types and type stubs. If you see any parts of this documentation that should be incorporated into the PEP, please feel free to borrow or outright plagiarize. 😊 Likewise, if you see anything in our documentation that you disagree with, please let us know so we can discuss.)

**Comment by srittau** [comment] 2021-01-18 13:00
I also held the opinion that inline annotations are preferable to separate stubs. Lately this opinion has changed a bit, possibly due to exposure to the `index.d.ts` files in JavaScript-land. I have come to like the idea of separate stubs files as a comprehensive, but concise description of a package's public API. Ideally automatically created at build time. I can't really pinpoint why this has changed, though, or verbalize why I prefer it like this.

I agree that the PEP would probably be the place to discuss an eventual consensus about this. But this is something that I would also prefer to delay to after the initial publishing of the PEP. I think it would also make sense to discuss this on typing-sig first to reach that consensus.

**Comment by erictraut** [comment] 2021-01-18 17:12
My viewpoint on this has changed over time too but in the opposite direction. My perspective started to change when I solicited input from library authors on this topic. They're pretty universally resistant to the idea of maintaining stubs separately from their code.

Likewise, we've found that the majority of Python developers are confused by — and dislike — stub files. They are conditioned to look in the source code for documentation and to gain a deeper understanding of how the code works.

And finally, there are a bunch of difficult tooling issues that arise when type stubs are maintained separately from the code. In TypeScript, this has not been as big a problem because .d.ts files are often generated as part of the build process for a library, and there is a single source of truth.

I think it's fine to have this discussion in the typing-sig, but we're going to push very hard for the viewpoint that inlined types should be used wherever possible. We're pretty convicted on this point based on our experience developing pyright and pylance the significant feedback we've received from both library authors and users.

**Comment by gvanrossum** [comment] 2021-01-18 18:06
Although an interesting data point may be Pandas, which is moving towards inline types but for which the Pylance team had previously developed a series of stubs: one reason to prefer stubs there is that docstrings in the Pandas source are templatized to the point where the docstrings you can extract *without running the code* are not very useful. It would be nice if tooling for generating stubs would be able to get the docstrings from the runtime. (This may be a per-project flag for such a tool.)

**Comment by erictraut** [comment] 2021-01-18 18:15
We really don't want to run the code on the user's machine to extract docstrings — for both performance and security reasons. We could ask the user for permission on a package-by-package basis, but that would be a pretty cumbersome user experience. I think we need a way to extract this information statically.

I'm encouraged by the direction that Pandas is heading. If nothing else, it should serve as an interesting case study that could help inform this discussion.

**Comment by srittau** [comment] 2021-01-25 11:59
It seems to me that part of the problem is the lack of tooling for extracting type stubs in the Python landscape. I don't think we should recommend either to use or to avoid type stubs for now in the PEP at this point, but this is certainly something we should keep an eye on.

**Closed as completed by srittau** 2021-01-25 11:59 UTC
